services:
  movie-convert:
    image: ianfrye/movie-convert:latest
    container_name: movie-convert
    volumes:
      - /docker/appdata/movie-convert/input/:/app/input
      - /docker/appdata/movie-convert/output/:/app/output
    restart: unless-stopped
